usr/lib/rpi-swap/bin/* usr/lib/rpi-swap/bin
etc/rpi/swap.conf etc/rpi/
lib/systemd/system-generators/rpi-swap-generator usr/lib/systemd/system-generators/
lib/systemd/zram-generator.conf.d/20-rpi-swap-zram0-ctrl.conf usr/lib/systemd/zram-generator.conf.d
lib/systemd/system/rpi-resize-swap-file.service usr/lib/systemd/system
lib/systemd/system/rpi-zram-writeback.service usr/lib/systemd/system
lib/systemd/system/rpi-remove-swap-file@.service usr/lib/systemd/system
